export const LIMIT_QUANTITY_TOPICS = 4;
export const LIMIT_ROW_PROBLEMS_TABLE = 20;
export const WEEKS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
export const ORIGINAL_API_URL = 'http://localhost:8000';
export const DEFAULT_LOTTIE_OPTIONS = {
  loop: true,
  autoplay: true,
  rendererSettings: {
    preserveAspectRatio: 'xMidYMid slice',
  },
};
export const PROBLEMS_SAMPLE = [
  {
    id: 0,
    name: 'Two Sum',
    status: 'Todo',
    acceptance: 38.27,
    difficulty: 'Easy',
    topics: ['Array', 'Math', 'Counting'],
  },
  {
    id: 1,
    name: 'Sort Banana',
    status: 'Solved',
    acceptance: 34.29,
    difficulty: 'Normal',
    topics: ['Sorting', 'Counting'],
  },
  {
    id: 2,
    name: 'Search Pig Film',
    status: 'Attempted',
    acceptance: 42.57,
    difficulty: 'Hard',
    topics: ['Searching'],
  },
  {
    id: 3,
    name: 'Palindrome Checker',
    status: 'Todo',
    acceptance: 27.24,
    difficulty: 'Easy',
    topics: ['String'],
  },
  {
    id: 4,
    name: 'FizzBuzz',
    status: 'Todo',
    acceptance: 35.67,
    difficulty: 'Easy',
    topics: ['Math'],
  },
  {
    id: 5,
    name: 'Reverse Array',
    status: 'Todo',
    acceptance: 17.82,
    difficulty: 'Normal',
    topics: ['Array'],
  },
  {
    id: 6,
    name: 'Factorial Calculator',
    status: 'Attempted',
    acceptance: 14.28,
    difficulty: 'Normal',
    topics: ['Math', 'Recursion'],
  },
  {
    id: 7,
    name: 'Find Prime Numbers',
    status: 'Todo',
    acceptance: 85.36,
    difficulty: 'Hard',
    topics: ['Math', 'Searching'],
  },
  {
    id: 8,
    name: 'Validate Email Addresses',
    status: 'Solved',
    acceptance: 11.27,
    difficulty: 'Normal',
    topics: ['String', 'Regex'],
  },
  {
    id: 9,
    name: 'Calculate Fibonacci Sequence',
    status: 'Solved',
    acceptance: 35.25,
    difficulty: 'Hard',
    topics: ['Math', 'Recursion'],
  },
  {
    id: 10,
    name: 'Implement Binary Search',
    status: 'Attempted',
    acceptance: 28.92,
    difficulty: 'Normal',
    topics: ['Array', 'Searching'],
  },
  {
    id: 11,
    name: 'Convert Roman Numerals to Integer',
    status: 'Todo',
    acceptance: 15.36,
    difficulty: 'Normal',
    topics: ['String', 'Math'],
  },
  {
    id: 12,
    name: 'Generate Random Passwords',
    status: 'Todo',
    acceptance: 35.01,
    difficulty: 'Easy',
    topics: ['String', 'Random'],
  },
  {
    id: 13,
    name: 'Check Anagrams',
    status: 'Todo',
    acceptance: 25.78,
    difficulty: 'Normal',
    topics: ['String'],
  },
  {
    id: 14,
    name: 'Calculate Area of Shapes',
    status: 'Todo',
    acceptance: 12.35,
    difficulty: 'Normal',
    topics: ['Math', 'Geometry'],
  },
  {
    id: 15,
    name: 'Implement Stack Data Structure',
    status: 'Todo',
    acceptance: 24.37,
    difficulty: 'Hard',
    topics: ['Data Structures'],
  },
  {
    id: 16,
    name: 'Find Longest Common Prefix',
    status: 'Todo',
    acceptance: 22.45,
    difficulty: 'Normal',
    topics: ['String'],
  },
  {
    id: 17,
    name: 'Calculate Factorial using Iteration',
    status: 'Todo',
    acceptance: 12.24,
    difficulty: 'Easy',
    topics: ['Math', 'Looping'],
  },
  {
    id: 18,
    name: 'Implement Queue Data Structure',
    status: 'Todo',
    acceptance: 35.36,
    difficulty: 'Normal',
    topics: ['Data Structures'],
  },
  {
    id: 19,
    name: 'Check Balanced Parentheses',
    status: 'Todo',
    acceptance: 37.4,
    difficulty: 'Normal',
    topics: ['String', 'Stack'],
  },
  {
    id: 20,
    name: 'Find Missing Number in Array',
    status: 'Todo',
    acceptance: 24.25,
    difficulty: 'Hard',
    topics: ['Array', 'Math'],
  },
  {
    id: 21,
    name: 'Count Cat In My House',
    status: 'Todo',
    acceptance: 14.23,
    difficulty: 'Hard',
    topics: ['Array', 'Couting'],
  },
  {
    id: 22,
    name: 'Find Cat in Bushes',
    status: 'Todo',
    acceptance: 9.25,
    difficulty: 'Hard',
    topics: ['Array', 'Searching'],
  },
];
export const TOPICS_SAMPLE = [
  { id: 0, name: 'String', quantity: 22 },
  { id: 1, name: 'Array', quantity: 56 },
  { id: 2, name: 'Sorting', quantity: 18 },
  { id: 3, name: 'Math', quantity: 9 },
  { id: 4, name: 'Counting', quantity: 27 },
  { id: 5, name: 'Searching', quantity: 9 },
  { id: 6, name: 'Recursion', quantity: 26 },
  { id: 7, name: 'Regex', quantity: 11 },
  { id: 8, name: 'Random', quantity: 21 },
  { id: 9, name: 'Stack', quantity: 18 },
  { id: 10, name: 'Geometry', quantity: 6 },
  { id: 11, name: 'Data Structures', quantity: 2 },
  { id: 12, name: 'Looping', quantity: 7 },
];

export const STATISTICSDATASETS_SAMPLE = {
  totalEasy: 35,
  totalNormal: 12,
  totalHard: 5,
  Easy: [12, 2, 0, 2, 5, 6, 7],
  Normal: [8, 2, 5, 6, 8, 2, 0],
  Hard: [0, 1, 5, 6, 4, 8, 1],
};

export const USER_SAMPLE = {
  id: '12444',
  fullName: 'Nguyễn Trường An',
  phoneNumber: '032442215',
  dateOfBirth: '28/12/2003',
  email: 'ndgdh@gmail.com',
  avatarSrc: '',
};

export const DATA_LOGIN_SAMPLE = {
  token:
    'eyJhbGciOiJIUzI1NiJ9.eyJwaG9uZU51bWJlciI6IjA5NjExNjI5NzkiLCJ1c2VySWQiOjIsImVtYWlsIjoibmd1eWVuZHFkdXlAZ21haWwuY29tIiwic3ViIjoiMDk2MTE2Mjk3OSIsImV4cCI6MTcxNTYxNTMzM30.xw2DthsajQoFeMpkTvXXPcSIxHgT5LVAB0oMxtWDgF8',
  user: {
    id: 1,
    fullName: 'Nguyễn Đình Quốc Duy',
    phoneNumber: '0961162979',
    dateOfBirth: '1990-01-01T00:00:00',
    email: 'nguyendqduy@gmail.com',
    password: '$2a$10$QUyg4P9ogx6aX40V4YbzYu7/8kT/q7epP6/ITBe1fY3Rcxuh/.pLq',
    cumulativeScore: 0.0,
    addedAt: '1990-01-01T00:00:00',
    updatedAt: '1990-01-01T12:34:56',
    role: 'USER',
    avatarSrc: '',
  },
};

export const EMOJI_COMMENT = {
  love: { emoji: '❤️', name: 'Love' },
  woww: { emoji: '😲', name: 'Woww' },
  humm: { emoji: '🙄', name: 'Humm' },
  haha: { emoji: '😆', name: 'Haha' },
  huhu: { emoji: '😭', name: 'Huhu' },
  angry: { emoji: '😡', name: 'Angry' },
};

export const COMMENTS_SAMPLE = [
  {
    id: 1,
    text: 'Bạn Trường An rất là đẹp trai và dthw !',
    updateAt: '1th5 21:41',
    userName: 'Nguyễn Văn Hoàng',
    emoji: EMOJI_COMMENT.love,
    emojiQuantity: 99,
    replyComments: [
      {
        id: 2,
        text: 'Cảm ơn bạn nhiều nha <3 love',
        updateAt: '1th5 21:44',
        userName: 'Nguyễn Trường An',
        emoji: EMOJI_COMMENT.haha,
        emojiQuantity: 8,
        replyComments: [],
      },
      {
        id: 5,
        text: 'Cảm ơn bạn nhiều nha <3 love',
        updateAt: '1th5 21:44',
        userName: 'Nguyễn Trường An',
        emoji: EMOJI_COMMENT.haha,
        emojiQuantity: 8,
        replyComments: [],
      },
    ],
  },
  {
    id: 3,
    text: 'Bài code này khó quá, thằng nào tạo ra nó vậy????',
    updateAt: '1th5 21:47',
    userName: 'Trần Văn An',
    emoji: EMOJI_COMMENT.angry,
    emojiQuantity: 5,
    replyComments: [
      {
        id: 4,
        text: 'T tạo nè m có ý kiến gì hemmm thằng đần này????',
        updateAt: '1th5 21:48',
        userName: 'Nguyễn Đình Quốc Duy',
        emoji: EMOJI_COMMENT.humm,
        emojiQuantity: 1,
        replyComments: [
          {
            id: 6,
            text: 'Cảm ơn bạn nhiều nha <3 love',
            updateAt: '1th5 21:44',
            userName: 'Nguyễn Trường An',
            emoji: EMOJI_COMMENT.haha,
            emojiQuantity: 8,
            replyComments: [],
          },
        ],
      },
    ],
  },
];

export const FILTER_DEFAULT = {
  userId: '1',
  pageNumber: '0',
  limit: LIMIT_ROW_PROBLEMS_TABLE,
  status: 'ALL',
  difficulty: 'ALL',
  topic: 'ALL',
  searchTerm: '',
};
