version: "3.8"

services:
  code-solution-fe:
    container_name: code-solution-fe
    image: code-solution-fe
    ports:
      - "3000:3000"
    environment: 
      REACT_APP_BASE_API_URL: http://localhost:8000
    networks:
      - code-solution-network

networks:
  code-solution-network:
    driver: bridge


