version: '3.8'
services:
    code-solution-db:
        image: postgres:latest
        container_name: code-solution-db
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: CodeSolution
        ports:
            - "5432:5432"
        volumes:
            - code-solution-data:/var/lib/postgresql

volumes:
    code-solution-data: