version: '3.8'
services:
  code-solution-db:
    image: postgres:latest
    container_name: code-solution-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: CodeSolution
    ports:
      - "5432:5432"
    volumes:
      - code-solution-data:/var/lib/postgresql
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "82:80"
    depends_on:
      - code-solution-db
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - pgnetwork

volumes:
  code-solution-data:

networks:
  pgnetwork:
    driver: bridge