server:
    port: 8000

    prod:
        url: ${PROD_BASE_URL}

spring:
    application:
        name: chat-hub-app

    devtools:
        livereload:
            enabled: true
    datasource:
        url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
        username: ${PROD_DB_USER}
        password: ${PROD_DB_PASSWORD}
        driverClassName: org.postgresql.Driver
    sql:
        init:
            mode: always
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        open-in-view: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
    file:
        name: mylog.log
    level:
        root: info

frontend:
    url: ${PROD_FRONTEND_URL}